### PR TITLE
Fixes the dcdr-js client's file watcher

### PR DESCRIPTION
**Pull request by stateoflux**
I discovered that the `dcdr-js` client was not responding to any changes made to the underlying decider.json file. The client was using node's `fs.watch` to implement its file watching capability, but turns out `fs.watch` is notoriously [buggy](https://github.com/nodejs/node/search?p=1&q=fs.watch&type=Issues).  I've replaced `fs.watch` with the [chokidar](https://github.com/paulmillr/chokidar) library (note this library used by many of the js build systems out there), which is a wrapper around the `fs.watch` but fixes its shortcomings.  I've also written a unit test to cover file watching functionality.

### CODE REVIEW

**Review by bshackelford — APPROVED** [review]
Nice. Thank you.

**Review by promiseofcake — APPROVED** [review]
Thanks. Only question would be whether or not we want to commit `package-lock.json` since we aren't currently targeting builds > Node `6` for this repo. If we have use-cases for newer versions it might make sense to add them to build build matrix.

**Comment by stateoflux** [comment]
@promiseofcake I've removed the `package-lock.json`

**Comment by promiseofcake** [comment]
Thanks @stateoflux, I think if we are using this in newer node deployments we can also increment the build matrix / deprecate old builds if desired.

**Pull request merged**
